### PR TITLE
Allow to share folders without linking them.

### PR DESCRIPTION
**Pull request by calavera**
This PR also fix a problem when the guestpath already exists.

### CODE REVIEW

**Comment by calavera** [comment]
@lstoll I'm going to merge this. The double linking issue because it doesn't remove the guestpath if it exists is really annoying.

**Comment by lstoll** [comment]
@calavera want me to cut a release?

**Comment by calavera** [comment]
Yes, please.

**Comment by lstoll** [comment]
0.4.5 pushed.

What's your email on rubygems.org? Will add you as an owner now.

**Comment by calavera** [comment]
david.calavera@gmail.com

**Comment by lstoll** [comment]
Added. release as you see fit.

**Pull request merged**
